# fly.toml app configuration file generated for django-car on 2023-11-28T09:24:26-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "django-car"
primary_region = "lax"
console_command = "/code/manage.py shell"

[build]

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
